-- Wazue v2 database. Run in a fresh Supabase project.
create table if not exists public.users (
  username text primary key,
  password_hash text not null,
  balance bigint not null default 0 check (balance >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  username text not null references public.users(username) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists sessions_username_idx on public.sessions(username);
create index if not exists sessions_expiry_idx on public.sessions(expires_at);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  description text not null default '',
  category text not null default 'Khác',
  price bigint not null check (price > 0),
  days integer,
  provider text not null default 'manual',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.deposits (
  id bigint generated by default as identity primary key,
  username text not null references public.users(username) on delete cascade,
  trans_code text not null unique,
  amount bigint not null check (amount > 0),
  status text not null default 'PENDING' check (status in ('PENDING','COMPLETED','CANCELLED')),
  provider_transaction_id text unique,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  username text not null references public.users(username) on delete cascade,
  order_code text not null unique,
  product_id bigint references public.products(id),
  product_name text not null,
  amount bigint not null check (amount > 0),
  status text not null default 'PENDING' check (status in ('PENDING','COMPLETED','CANCELLED','FAILED')),
  account text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  username text not null references public.users(username) on delete cascade,
  type text not null check (type in ('DEPOSIT','PURCHASE','REFUND','ADJUSTMENT')),
  amount bigint not null,
  reference text,
  status text not null default 'COMPLETED',
  created_at timestamptz not null default now()
);
create unique index if not exists wallet_reference_unique on public.wallet_transactions(type,reference) where reference is not null;

alter table public.users enable row level security;
alter table public.sessions enable row level security;
alter table public.products enable row level security;
alter table public.deposits enable row level security;
alter table public.orders enable row level security;
alter table public.wallet_transactions enable row level security;

insert into public.products(slug,name,description,category,price,days,provider,sort_order)
values
('wazue-1-day','Wazue 1 Ngày','Gói sử dụng 1 ngày','Wazue',7000,1,'qling',1),
('wazue-5-day','Wazue 5 Ngày','Gói sử dụng 5 ngày','Wazue',25000,5,'qling',2),
('wazue-10-day','Wazue 10 Ngày','Gói sử dụng 10 ngày','Wazue',40000,10,'qling',3),
('wazue-20-day','Wazue 20 Ngày','Gói sử dụng 20 ngày','Wazue',70000,20,'qling',4),
('wazue-30-day','Wazue 30 Ngày','Gói sử dụng 30 ngày','Wazue',100000,30,'qling',5)
on conflict (slug) do nothing;

create or replace function public.credit_deposit(p_deposit_id bigint,p_transaction_id text)
returns boolean language plpgsql security definer set search_path=public as $$
declare d deposits%rowtype; done boolean;
begin
  select * into d from deposits where id=p_deposit_id for update;
  if not found or d.status <> 'PENDING' then return false; end if;
  if p_transaction_id is not null and exists(select 1 from deposits where provider_transaction_id=p_transaction_id) then return false; end if;
  update deposits set status='COMPLETED',provider_transaction_id=nullif(p_transaction_id,''),completed_at=now() where id=d.id;
  update users set balance=balance+d.amount where username=d.username;
  insert into wallet_transactions(username,type,amount,reference) values(d.username,'DEPOSIT',d.amount,coalesce(nullif(p_transaction_id,''),d.trans_code));
  return true;
end $$;

create or replace function public.purchase_product(p_username text,p_product_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p products%rowtype; u users%rowtype; code text;
begin
  select * into p from products where id=p_product_id and active=true for share;
  if not found then raise exception 'Sản phẩm không tồn tại'; end if;
  select * into u from users where username=p_username for update;
  if not found then raise exception 'Tài khoản không tồn tại'; end if;
  if u.balance < p.price then raise exception 'Số dư không đủ'; end if;
  code := 'WZ'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
  update users set balance=balance-p.price where username=p_username;
  insert into orders(username,order_code,product_id,product_name,amount,status) values(p_username,code,p.id,p.name,p.price,'PENDING');
  insert into wallet_transactions(username,type,amount,reference) values(p_username,'PURCHASE',-p.price,code);
  return jsonb_build_object('success',true,'orderCode',code,'balance',u.balance-p.price,'product',p.name);
end $$;

-- Optional cleanup for expired sessions.
delete from public.sessions where expires_at < now();

create or replace function public.reserve_purchase(p_username text,p_product_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p products%rowtype; u users%rowtype; code text; oid bigint; nb bigint;
begin
 select * into p from products where id=p_product_id and active=true for share; if not found then raise exception 'Sản phẩm không tồn tại'; end if;
 select * into u from users where username=p_username for update; if not found then raise exception 'Tài khoản không tồn tại'; end if;
 if u.balance < p.price then raise exception 'Số dư không đủ'; end if;
 code:='WZ'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
 nb:=u.balance-p.price; update users set balance=nb where username=p_username;
 insert into orders(username,order_code,product_id,product_name,amount,status) values(p_username,code,p.id,p.name,p.price,'PENDING') returning id into oid;
 insert into wallet_transactions(username,type,amount,reference,status) values(p_username,'PURCHASE',-p.price,code,'COMPLETED');
 return jsonb_build_object('success',true,'orderId',oid,'orderCode',code,'balance',nb);
end $$;

create or replace function public.complete_purchase(p_order_id bigint,p_account text)
returns boolean language plpgsql security definer set search_path=public as $$
begin update orders set status='COMPLETED',account=p_account,completed_at=now() where id=p_order_id and status='PENDING'; return found; end $$;

create or replace function public.cancel_purchase(p_order_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
declare o orders%rowtype; begin select * into o from orders where id=p_order_id for update; if not found or o.status<>'PENDING' then return false; end if; update orders set status='CANCELLED' where id=o.id; update users set balance=balance+o.amount where username=o.username; insert into wallet_transactions(username,type,amount,reference) values(o.username,'REFUND',o.amount,o.order_code); return true; end $$;
